name: isce3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - backoff
  - cmake>=3.18
  - cxx-compiler
  - eigen>=3.3
  - fftw>=3.3
  - gdal>=3
  - gmock>=1.10
  - gtest>=1.10
  - h5py>=3
  - hdf5>=1.10.2,!=1.14.0
  - libgdal-hdf5
  - libgdal-netcdf
  - ninja
  - numpy>=1.20
  - pyaps3>=0.3
  - pybind11>=2.5
  - pyre>=1.12.5
  - pysolid>=0.2
  - pytest
  - python>=3.8
  - raider-base>=0.4.5
  - ruamel.yaml
  - scipy!=1.10.0
  - shapely>=2
  - snaphu>=0.4
  - yamale
