name: isce3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - backoff
  - cmake=3.18
  - cxx-compiler
  - eigen=3.3
  - fftw=3.3
  - gdal=3.0
  - gmock=1.10
  - gtest=1.10
  - h5py=3.1
  - hdf5=1.10.6
  - ninja
  - numpy=1.20
  - pyaps3=0.3
  - pybind11=2.5
  # pyre not included in this build
  - pytest
  - python=3.8
  - ruamel.yaml
  - scipy!=1.10.0
  - shapely
  - yamale