name: isce3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - backoff
  - cmake=3.19
  - gxx_linux-64=11
  - eigen=3.3
  - fftw=3.3
  # GDAL 3.0 is too old to satisfy python>=3.9
  # GDAL 3.1 is too old to satisfy hdf5>=1.12
  # GDAL 3.6.0 was the first to build with cmake, needed for FindGDAL module
  # https://github.com/conda-forge/gdal-feedstock/pull/651
  - gdal>=3.6
  - gmock=1.10
  - gtest=1.10
  - h5py
  - hdf5
  - ninja
  - numpy
  # Needed to resolve against numpy <1.22,
  # see https://github.com/conda-forge/pandas-feedstock/issues/208
  - pandas<2.2
  - pyaps3=0.3
  - pybind11=2.6
  # pyre not included in this build
  - pysolid
  - pytest
  - python
  - ruamel.yaml
  - scipy!=1.10.0
  - shapely
  - snaphu=0.4
  - yamale
