name: isce3
channels:
  - conda-forge
  - nodefaults
dependencies:
  - backoff
  - cmake=3.19
  - gxx_linux-64=11
  - eigen=3.3
  - fftw=3.3
  # GDAL 3.0 is too old to satisfy python>=3.9
  - gdal=3.1
  - gmock=1.10
  - gtest=1.10
  - h5py=3.6
  - hdf5=1.12.1
  - ninja
  - numpy=1.20
  - pandas
  - pyaps3=0.3
  - pybind11=2.6
  # pyre not included in this build
  - pysolid
  - pytest
  - python=3.9
  - ruamel.yaml
  - scipy!=1.10.0
  - shapely=1.8
  - snaphu=0.4
  - yamale
